# -*- coding: utf-8 -*-
"""
Dana's Brain - Autonomous Marketing AI Agents
Main Chainlit application with full UI implementation
Version: 1.0 - RAG Implementation
"""

import sys
import io
import chainlit as cl
from chainlit.input_widget import Select, TextInput
from crewai import Crew, Process
import os
from pathlib import Path
from dotenv import load_dotenv

# Set UTF-8 encoding for Windows console
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# Load environment variables
load_dotenv()

# Import agents and tasks
from agents.strategy_architect import strategy_architect
from agents.dana_copywriter import dana_copywriter
from tasks.strategy_tasks import create_strategy_task
from tasks.copywriting_tasks import create_copywriting_task

# Import TXTSearchTool initialization
from tools.txt_search_tools import initialize_all_tools
from datetime import datetime

# Initialize tools ONCE at startup (global state)
TOOLS = None


@cl.on_chat_start
async def start():
    """Initialize chat with form inputs and tools"""
    global TOOLS

    # Initialize TXTSearchTools on first run
    if TOOLS is None:
        await cl.Message(content="🔧 Initializing RAG search tools...").send()
        try:
            TOOLS = await cl.make_async(initialize_all_tools)()
            await cl.Message(content="✅ Search tools ready! ChromaDB initialized.").send()
        except Exception as e:
            await cl.Message(content=f"❌ Error initializing tools: {str(e)}").send()
            return

    settings = await cl.ChatSettings([
        TextInput(
            id="product",
            label="Product Name / Service",
            placeholder="Example: Lierac Hydragenist Serum"
        ),
        TextInput(
            id="benefits",
            label="Key Benefits",
            placeholder="Example: Deep hydration, instant glow, natural ingredients"
        ),
        TextInput(
            id="audience",
            label="Target Audience",
            placeholder="Example: Women 35-50, interested in anti-aging"
        ),
        TextInput(
            id="offer",
            label="The Offer",
            placeholder="Example: 25% discount + free shipping"
        ),
        Select(
            id="persona",
            label="Select Dana Persona",
            values=[
                "Professional Dana",
                "Friendly Dana",
                "Inspirational Dana",
                "Mentor Dana"
            ],
            initial_value="Friendly Dana"
        )
    ]).send()

    cl.user_session.set("settings", settings)

    await cl.Message(content="""# 🧠 Welcome to "Dana's Brain" (RAG-Powered)

I'm an AI system that creates Hebrew marketing content in Dana's unique style.

## 📱 What I Create:

**9 Ready-to-Publish Posts:**
- 3 LinkedIn posts (professional & warm)
- 3 Facebook posts (personal & storytelling)
- 3 Instagram posts (short & catchy)

## 🚀 How It Works:

1. **Fill the form above** ↑ with your product details
2. **Choose a persona** - which Dana style suits you?
3. **Send any message** (e.g., "Let's start")
4. **Wait 2-3 minutes** - my agents are working with RAG search!

## ✨ What You'll Get:

✅ Strategic brief in Hebrew
✅ 9 posts tailored for each platform
✅ Transparent agent workflow
✅ **NEW:** Dynamic search through Dana's knowledge base
✅ **NEW:** Saved MD file in outputs/ folder

---

**Let's begin!** 💪""").send()


@cl.on_settings_update
async def update_settings(settings):
    """Update settings when user changes them"""
    cl.user_session.set("settings", settings)


async def save_output_to_file(product, persona, content, strategy):
    """
    Save the generated content to a markdown file
    """
    try:
        # Create outputs directory if not exists
        output_dir = Path(__file__).parent / "outputs"
        output_dir.mkdir(exist_ok=True)

        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_product = "".join(c for c in product if c.isalnum() or c in (' ', '-', '_')).strip()[:50]
        filename = f"{timestamp}_{safe_product}_{persona.replace(' ', '_')}.md"
        filepath = output_dir / filename

        # Format markdown content
        md_content = f"""# Marketing Content Output

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Product:** {product}
**Persona:** {persona}

---

## 🎯 Strategic Brief

{strategy}

---

## ✍️ Social Media Posts

{content}

---

**Generated by Dana's Brain - Chainlit + CrewAI with RAG**
"""

        # Write to file with UTF-8 encoding (for Hebrew)
        filepath.write_text(md_content, encoding='utf-8')

        await cl.Message(content=f"💾 **Output saved to:** `{filepath}`").send()

    except Exception as e:
        await cl.Message(content=f"⚠️ Could not save file: {str(e)}").send()


@cl.on_message
async def main(message: cl.Message):
    """Process user request with CrewAI"""
    settings = cl.user_session.get("settings")

    # Extract and validate inputs
    product = settings.get("product", "").strip()
    benefits = settings.get("benefits", "").strip()
    audience = settings.get("audience", "").strip()
    offer = settings.get("offer", "").strip()
    persona = settings.get("persona", "Friendly Dana")

    # Validate that all required fields are filled
    if not all([product, benefits, audience, offer]):
        await cl.Message(content="""❌ **Error: Missing Data**

Please fill in **all fields** in the form above:
- Product Name / Service
- Key Benefits
- Target Audience
- The Offer

Then send another message to activate the system.""").send()
        return

    # Show loading message
    msg = cl.Message(content=f"""🔄 **Dana's Team Started Working!**

**Product:** {product}
**Target Audience:** {audience}
**Persona:** {persona}

⏳ This may take 2-3 minutes...

**What's happening now:**
1. 🎯 The Strategist is searching methodology and analyzing product data
2. ✍️ Dana is searching voice examples and writing 9 tailored posts
3. 🎨 Adapting content for each platform with RAG

Please wait...""")
    await msg.send()

    # Prepare inputs for the crew
    inputs = {
        'product': product,
        'benefits': benefits,
        'audience': audience,
        'offer': offer,
        'persona': persona
    }

    # Inject TXTSearchTools into existing agents (RAG tools for dynamic search)
    global TOOLS
    strategy_architect.tools = [TOOLS["methodology"]]
    dana_copywriter.tools = [TOOLS["voice_examples"], TOOLS["style_guide"]]

    # Create tasks - agents will use RAG tools to search for relevant information
    strategy_task = create_strategy_task(strategy_architect, inputs)
    copywriting_task = create_copywriting_task(
        dana_copywriter,
        inputs,
        strategy_task
    )

    # Define synchronous crew execution function
    def run_crew():
        """Create and run the marketing crew"""
        try:
            # Assemble crew
            crew = Crew(
                agents=[strategy_architect, dana_copywriter],
                tasks=[strategy_task, copywriting_task],
                process=Process.sequential,
                verbose=False  # Reduced verbosity - RAG search happens in background
            )

            # Execute crew
            result = crew.kickoff(inputs=inputs)
            return result
        except Exception as e:
            raise Exception(f"Error running crew: {str(e)}")

    try:
        # Run crew asynchronously (CRITICAL: wrap sync function with cl.make_async)
        result = await cl.make_async(run_crew)()

        # Extract per-task outputs for transparency
        task_outputs = getattr(result, "tasks_output", []) or []

        def safe_attr(obj, names, default=""):
            for name in names:
                if hasattr(obj, name):
                    val = getattr(obj, name)
                    if val:
                        return val
            return default

        # Map task outputs by agent role for easier display
        agent_outputs = {}
        for t in task_outputs:
            agent_name = safe_attr(t, ["agent_role", "agent_name"])
            if not agent_name and hasattr(t, "agent") and hasattr(t.agent, "role"):
                agent_name = t.agent.role
            agent_name = agent_name or "Task"

            agent_outputs[agent_name] = {
                "task_description": safe_attr(t, ["description", "task_description"]),
                "output": safe_attr(t, ["output", "raw", "result", "final_answer"], default="(no output captured)")
            }

        # Fallback: pull outputs directly from task objects if tasks_output is empty
        def first_non_empty(*vals):
            for v in vals:
                if v:
                    return v
            return "(no output captured)"

        strategy_output = first_non_empty(
            agent_outputs.get(strategy_architect.role, {}).get("output"),
            getattr(strategy_task, "output", None)
        )
        copy_output = first_non_empty(
            agent_outputs.get(dana_copywriter.role, {}).get("output"),
            getattr(copywriting_task, "output", None)
        )

        # Choose a single final combined output to avoid duplication in the UI
        final_combined_output = copy_output or getattr(result, "raw", "(no final output captured)")

        # Save output to MD file
        await save_output_to_file(product, persona, final_combined_output, strategy_output)

        # Format and display output with full traceability
        output = f"""# ✅ Project Completed Successfully!

---

## 🧾 Final Combined Output
{final_combined_output}

---

## 🔍 What Happened (Step-by-Step)
- Strategy task executed by **{strategy_architect.role}**
- Copywriting task executed by **{dana_copywriter.role}** (using strategy output as context)

---

## 📑 Data Provided
- Product: {product}
- Benefits: {benefits}
- Audience: {audience}
- Offer: {offer}
- Persona: {persona}

---

## 🧭 Task Prompts (for fine-tuning)
### Strategy Task Prompt
{strategy_task.description}

**Expected output format:**  
{strategy_task.expected_output}

---

### Copywriting Task Prompt
{copywriting_task.description}

**Expected output format:**  
{copywriting_task.expected_output}

---

## 🗂️ Agent Outputs
### 🎯 {strategy_architect.role}
{strategy_output}

---

### ✍️ {dana_copywriter.role}
{"(see Final Combined Output above)" if str(copy_output).strip() == str(final_combined_output).strip() else copy_output}

---

## 📊 Agent Workflow

### 🎯 Strategy Architect
**Role:** Business analysis and strategic brief creation

**What it did:**
- ✅ Analyzed product "{product}" and target audience
- ✅ Identified gaps and marketing opportunities
- ✅ Created comprehensive strategic brief in Hebrew
- ✅ Defined recommendations for each platform (LinkedIn, Facebook, Instagram)

**Tools used:**
- 📚 Dana_Brain_Methodology.txt

---

### ✍️ Dana (The Copywriter)
**Role:** Marketing content creation in Dana's voice

**What she did:**
- ✅ Read and understood the strategic brief
- ✅ Wrote 9 tailored posts (3 per platform)
- ✅ Adapted tone to persona: **{persona}**
- ✅ Maintained authenticity and Dana's unique voice

**Tools used:**
- 📚 Dana_Voice_Examples_Lierac.txt
- 📚 style_guide_customer_Lierac.txt

---

## 🎉 Done! Content Ready to Use

**What to do now?**
1. Review the content above ↑
2. Copy the posts you like
3. Publish on relevant platforms
4. **Check the saved MD file in outputs/ folder!**

💡 **Tip:** You can send another message with different data to get more content!"""

        msg.content = output
        await msg.update()

    except Exception as e:
        # Error handling with clear messages
        error_details = str(e)
        error_msg = f"""❌ **System Error**

**Error details:**
{error_details}

---

## 🔍 Recommended Checks:

1. **Check API Key:**
   - Open the `.env` file
   - Verify `OPENAI_API_KEY` is set correctly
   - Format: `OPENAI_API_KEY=sk-...`

2. **Check Data files:**
   - Dana_Brain_Methodology.txt
   - Dana_Voice_Examples_Lierac.txt
   - style_guide_customer_Lierac.txt

3. **Check internet connection**

---

**Need help?** Try again or check the logs for more info."""

        msg.content = error_msg
        await msg.update()


if __name__ == "__main__":
    from chainlit.cli import run_chainlit
    run_chainlit(__file__)
