-- Feedback table matching actual SQLite schema
-- Run this in Supabase SQL Editor to replace the incorrect schema

-- Drop existing table if needed (WARNING: deletes data!)
DROP TABLE IF EXISTS feedback CASCADE;

-- Create table with correct schema
CREATE TABLE feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id TEXT NOT NULL,
    content TEXT NOT NULL,
    rating INTEGER,
    category TEXT,
    raw_text_feedback TEXT,
    client_id TEXT NOT NULL DEFAULT 'Lierac',
    agent_type TEXT NOT NULL DEFAULT 'copywriter',
    persona TEXT NOT NULL,
    platform TEXT NOT NULL,
    archetype TEXT NOT NULL,
    rag_queries_used TEXT,
    metadata TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'pending_refinement', 'rejected', 'in_review')),
    confidence_score REAL CHECK (confidence_score IS NULL OR (confidence_score BETWEEN 0.0 AND 1.0)),
    refinement_data TEXT,
    lab_entry_date TIMESTAMP,
    actionability_score REAL CHECK (actionability_score IS NULL OR (actionability_score BETWEEN 0.0 AND 1.0)),
    created_at TIMESTAMP DEFAULT NOW(),
    reviewed_at TIMESTAMP,
    notes TEXT
);

-- Indexes for performance
CREATE INDEX idx_feedback_post_id ON feedback(post_id);
CREATE INDEX idx_feedback_status ON feedback(status);
CREATE INDEX idx_feedback_created_at ON feedback(created_at DESC);
CREATE INDEX idx_feedback_platform ON feedback(platform);
CREATE INDEX idx_feedback_client_id ON feedback(client_id);
CREATE INDEX idx_feedback_persona ON feedback(persona);

-- Enable Row Level Security (RLS)
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Policy to allow all operations (adjust for production)
CREATE POLICY "Allow all for authenticated users" ON feedback
    FOR ALL USING (true);

-- Optional: Add a comment
COMMENT ON TABLE feedback IS 'Stores user feedback for content generated by Dana''s Brain';
